apiVersion: v1
kind: Service
metadata:
  name: redis-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: redis-api
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-api
  labels:
    app: redis-api
spec:
  containers:
  - name: master
    image: docker.io/vinhags/redis-api
    env:
    - name: REDIS_HOST
      value: "redis"
    - name: REDIS_PORT
      value: "6379"
    imagePullPolicy: Always
    ports:
    - containerPort: 7379
